name: EC2 CD Pipeline on AWS

on:
  workflow_run:
    workflows: ['Docker CI for Docker Hub Pipeline']
    types:
      - completed

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull Docker image
        run: sudo docker pull carloshernandezcruz/shadcn-table:latest

      - name: Delete Old docker container
        run: sudo docker rm -f shadcn-table-container || true

      - name: Run Docker Container
        run: sudo docker run -d -p 8080:8080 --name shadcn-table-container carloshernandezcruz/shadcn-table
